name: PR

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target lint -t algorithms-lint -f docker/interviewing.Dockerfile .
      - run: docker run algorithms-lint

  algorithms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target algorithms -t algorithms-ci -f docker/interviewing.Dockerfile .
      - run: docker run algorithms-ci
